# Generated by Django 5.0 on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_budget_currency_project_budget_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='revision_limit',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
