# Generated by Django 5.0 on 2026-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_revision_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='initiated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
