# Generated by Django 5.0 on 2026-06-06 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_initiated_at_alter_project_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='initiated_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
