# Generated by Django 5.0 on 2026-05-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_fileupload_file_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
