# Generated by Django 5.0 on 2026-05-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-submitted_at']},
        ),
    ]
