# Generated by Django 5.0 on 2026-04-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_client'),
        ('project_messages', '0003_rename_content_message_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedback'),
        ),
    ]
