# Generated by Django 5.0 on 2026-05-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed_at'),
        ('timelog', '0001_initial'),
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Start'), ('pause', 'Pause'), ('resume', 'Resume'), ('stop', 'Stop')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hours_logged', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='users.designer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tasks.task')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['designer', 'timestamp'], name='timelog_act_designe_bd0cfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused')], default='running', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('accumulated_secs', models.IntegerField(default=0)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to='users.designer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to='tasks.task')),
            ],
            options={
                'unique_together': {('designer', 'task')},
            },
        ),
    ]
